# Expose all calls MyHeat API has
---
get_devices:
  name: Get Devices
  description: Get all connected devices
  target: &tgt
    device:
      integration: myheat

get_device_info:
  name: Get Device Info
  description: Get device state
  target: *tgt
  fields:
    alt_device_id: &devid
      name: Device ID (API)
      description: Set custom device ID. Default to the device passed to a target.
      selector:
        number:

set_env_goal:
  name: Set environment goal (temperature)
  description: Set environment goal, or goal for mode.
  target: *tgt
  fields:
    obj_id: &objid
      name: Object ID
      description: Object ID, environment or engineering component.
      required: true
      selector:
        number:
    goal:
      name: Goal [temperature]
      description: Environment temperature goal
      required: true
      selector:
        number:
    alt_device_id: *devid
    change_mode: &chmode
      name: Change Mode
      description: |
        If set, then current enabled mode would be adjusted.
        If unset, then mode would be reset.
      default: false
      selector:
        boolean:

set_env_curve:
  name: Set environment to use goal curve
  description: Set goal curve for environment
  target: *tgt
  fields:
    obj_id: *objid
    curve:
      name: Curve ID
      description: ID of the temperature Curve to apply.
      required: true
      selector:
        number:
    alt_device_id: *devid
    change_mode: *chmode

set_eng_goal:
  name: Set engineering component goal
  description: Controls engineering component, like valves position, etc...
  target: *tgt
  fields:
    obj_id: *objid
    goal:
      name: Goal
      description: Component goal, e.g. 3-state valve position or something else.
      required: true
      selector:
        number:
    alt_device_id: *devid
    change_mode: *chmode

set_heating_mode:
  name: Set heating mode
  description: One of mode_id or schedule_id should be provided.
  target: *tgt
  fields:
    alt_device_id: *devid
    mode_id:
      name: Mode ID
      description: Select some heating mode
      selector:
        number:
    schedule_id:
      name: Schedule ID
      description: Select some schedule
      selector:
        number:

set_security_mode:
  name: Set security mode
  description: Arm/disarm security (mode)
  target: *tgt
  fields:
    mode:
      name: Mode
      description: Set security alarm mode.
      required: true
      selector:
        boolean:
    alt_device_id: *devid

refresh:
  name: Force refresh of the data coordinator
  description: Trigger coordinator data refresh
  target: *tgt
