name: Linting

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

env:
  DEFAULT_PYTHON: "3.14"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
      - name: Install Dependencies
        run: uv sync --frozen --all-groups
        shell: bash
      - name: Run pre-commit
        run: uv run pre-commit run --all-files --show-diff-on-failure --color=always
        shell: bash

  hacs:
    runs-on: "ubuntu-latest"
    name: HACS
    steps:
      - uses: actions/checkout@v7
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
          ignore: brands

  hassfest:
    runs-on: "ubuntu-latest"
    name: Hassfest
    steps:
      - uses: actions/checkout@v7
      - uses: "home-assistant/actions/hassfest@master"
