name: CI

on:
  push:
  pull_request:

env:
  DEFAULT_PYTHON: "3.13"

jobs:
  tests:
    runs-on: "ubuntu-latest"
    name: Run tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - uses: astral-sh/setup-uv@v6
      - name: Install Dependencies
        run: uv sync --frozen --all-groups
        shell: bash
      - name: Test with Pytest
        run: uv run pytest --cov-report=xml
        shell: bash
      # yamllint disable
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      # yamllint enable
